### PR TITLE
Fixed some issues that prevented things from working automatically.

### PR DESCRIPTION
**Pull request by kthompson**

### CODE REVIEW

**Comment by monokrome** [comment]
Looks good, but I think that binding events in the markup is better. Why did you decide to do this? Also, can you remove the `console.log` in `app.js`?

**Comment by kthompson** [comment]
App.js was never being require()'d so nothing was happening. I had to call require('app') in order to get the default setup working.

**Comment by monokrome** [comment]
@kthompson How about a `<script>require('app');</script>` instead? Are you opposed to that solution? I try to avoid DOM attributes for scripting behavior such as `onload`.

This pull request makes a lot of sense, either way, so I'll merge it. Just wondering if there's any reason to use the DOM attribute. Thanks a ton for the help!

**Comment by monokrome** [comment]
Thanks!

**Pull request merged**
